[colors.primary]
background = '#131313'
foreground = '#e2e2e2'
 
[colors.cursor]
text = '#e2e2e2'
cursor = '#c6c6c6' 
 
[colors.vi_mode_cursor]
text = '#131313'
cursor = '#91d888' 
 
[colors.search.matches]
foreground = '#474747' 
background = '#a0cfd3' 
 
[colors.search.focused_match]
foreground = '#474747' 
background = '#91d888' 
 
[colors.footer_bar]
foreground = '#474747' 
background = '#e2e2e2' 
 
[colors.hints.start]
foreground = '#474747' 
background = '#baccb3' 
 
[colors.hints.end]
foreground = '#474747' 
background = '#baccb3' 
 
[colors.selection]
text = '#131313'
background = '#91d888'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#91d888' 
yellow = '#2a6b29' 
blue = '#91d888' 
magenta = '#a0cfd3' 
cyan = '#baccb3' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 