[general]
import = [
  "~/.config/alacritty/catppuccin-latte.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 11.0

[window]
opacity = 0.9

[cursor]
thickness = 0.25

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor.vi_mode_style]
shape = "Underline"

